### ISSUE TITLE
Improve code security and fix code scanning alerts

### ISSUE THREAD

**Issue by aadictive** [aadictive/aadictive.github.io#67]
- [ ] - Missing rate limiting in master - [code-scanning#1](https://github.com/aadictive/aadictive.github.io/security/code-scanning/1)
- [ ] - Missing rate limiting in master - [code-scanning#2](https://github.com/aadictive/aadictive.github.io/security/code-scanning/2)
- [ ] - Missing rate limiting in master - [code-scanning#3](https://github.com/aadictive/aadictive.github.io/security/code-scanning/3)

Solution recommendation: **A rate-limiting middleware should be used to prevent such attacks.**
